    "import pandas as pd\n",
    "import cv2\n",
    "import pytesseract as tess\n",
    "import numpy as np\n",
    "import difflib as dl\n",
    "\n",
    "data = {\"ProductName\" : [\"Nova Moxine 800\", \"Neo Nova-500\", \n",
    "                         \"Tonamic\", \"Baytril 5%\", \"Biocatalin\", \"Hitagen-50\", \n",
    "                         \"Mezuri 5%\", \"Novacilan\", \"Lemisol\", \"Coccila\"],\n",
    "        \n",
    "        \"ProductPath\" : [\"Druge/Pic-0001.jpg\", \"Druge/Pic-0002.jpg\", \n",
    "                         \"Druge/Pic-0003.jpg\", \"Druge/Pic-0004.jpg\", \n",
    "                         \"Druge/Pic-0005.jpg\", \"Druge/Pic-0006.jpg\", \n",
    "                         \"Druge/Pic-0007.jpg\", \"Druge/Pic-0008.jpg\", \n",
    "                         \"Druge/Pic-0009.jpg\", \"Druge/Pic-0010.jpg\"]\n",
    "        \n",
    "        \"NameFlag\" : [\"['NOVA', 'MOXIN', '800']\",\"['NEO','NOVA-500']\",\n",
    "                      \"['TONAMIC']\",\"['Baytril','5%']\",\"['BIOCATALIN']\",\n",
    "                      \"['HITAGEN-50]\",\"['Mezuri','5%']\",\"['NOVACILAN']\",\n",
    "                      \"['LEMISOL']\",\"['COCCILA']\"]}\n",
    "dateFrame = pd.DataFrame(data, columns = [\"ProductName\", \"ProductPath\", \"NameFlag\"])\n",
    "\n",
    "#อย่าลืมเปลี่ยน path\n",
    "export_csv = daraFrame.to_csv(r'E:\\BANK\\Studies\\Programming Fundamentals\\Dek 64\\CPF Projects\\Medicine_Data.csv', index = False, header = True)"
 
